### ISSUE TITLE
Define required binary dependencies. e.g. minimum Kernel and Glibc version, and allow Symflower to work no matter the Glibc version

### ISSUE THREAD

**Issue by JukicDejan** [symflower/symflower#10]
Hi,

I get the following message when trying to run symflower from the command line:

``` symflower: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by symflower) ```

os-release yields:

```
 cat /etc/os-release
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

It would be nice to know which dependencies are needed and ideally that they also work with different versions of glibc, is there a way to make it work with the current glibc version?

**Comment by zimmski** [comment]
Can reproduce with

```
docker run -it --rm ubuntu:bionic bash
apt-get update
apt-get install -y curl
curl -sSLf https://get.symflower.com/install | sh
```

Gives

```
...
Verifying the installation:
/usr/local/bin/symflower: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/symflower)
```

```
ldd $(which symflower)
/usr/local/bin/symflower: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/symflower)
        linux-vdso.so.1 (0x00007ffe4d3d4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9406cfe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9406afa000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9406709000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9406f1d000)
```

**Comment by zimmski** [comment]
@JukicDejan The one reported is "bionic" which is 18.04.

In comparison the same with 20.04 (`docker run -it --rm ubuntu:focal bash`) works. Which has GLibc 2.31

**Comment by zimmski** [comment]
Works with 21.04 (`docker run -it --rm ubuntu:impish bash`) too. Which has GLibc 2.34 (you can check with `ldd --version`)

**Comment by zimmski** [comment]
@JukicDejan We should support Ubuntu 18.04 as it will be maintained by Canonical for a very long time. Let me get back to you about that.

Dependencies about system for all OSes will be added with this issue as well.

**Comment by zimmski** [comment]
Strange thing is that we support Debian 10 which has Glibc 2.28. So Ubuntu does something strange i do not understand yet .

**Comment by JukicDejan** [comment]
If it helps: ldd gives:

```
 ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by zimmski** [comment]
Ah right, my bad. Makes total sense i remembered the wrong Glibc version. We are looking into building our "symflower" binary completely statically for Linux. With that we should be able to drop the Glibc dependency.

**Comment by zimmski** [comment]
@JukicDejan Can you give it another try please. The newest version v22711 is now statically built, so it should work on your system. You can install it with `curl -sSLf https://get.symflower.com/install | sh` or in case you are using an editor plugin you need to check the version and might need to restart your editor.

**Comment by JukicDejan** [comment]
It works, thank you very much

**Comment by zimmski** [comment]
Will move the definitions of requirements for Symflower into its own issues.
