### ISSUE TITLE
Need to be able to configure maven settings

### ISSUE THREAD

**Issue by robertregina59** [symflower/symflower#13]
Attempting to run generate unit tests on an enterprise maven application. We have our own nexus server which stores many artifacts from private repos. When running the generate build it runs a maven command

Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xab, 0xeb, 0x59, 0x99, 0x18, 0xba, 0x11, 0xed, 0x95, 0xa8, 0x6c, 0x2b, 0x59, 0x68, 0x69, 0xe3}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace C:\workspaces\dctrack_app_3\server\
Search for Java files
Download Maven source dependencies for C:\workspaces\dctrack_app_3\server\pom.xml
Cannot download dependencies: Internal error: exit status 1:
[]string{"mvn", "--settings", "C:\\Users\\RobertRegina\\AppData\\Local\\JetBrains\\Toolbox\\apps\\IDEA-U\\ch-1\\222.3345.118.plugins\\symflower\\share\\install\\build\\cache\\maven/maven-settings.xml", "--file", "C:\\workspaces\\dctrack_app_3\\server\\pom.xml", "--batch-mode", "dependency:sources"}

Which fails with the error: 
[ERROR] Failed to execute goal on project CommonService: Could not resolve dependencies for project _OMITTED_ Failure to find _OMMITTED_ in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I tried to overrwrite the settings file above but it was rewritten on a new run, and I cannot determine how to change any settings for symflower via intellij.

**Comment by zimmski** [comment]
Thanks for the report.

The `maven-settings.xml` is a temporary file that we create to fetch sources of the Maven dependencies and save them locally. So changing it does indeed not result in Symflower fetching from another server. However, we are inheriting your local Maven configuration, so we might be simply missing something distinct of your setup.

Can you tell me how you currently configure your project to fetch from your Nexus server? Are you setting environment variables? Do you have an extra settings file for Maven? Is the configuration in the POM file directly? Every information towards your setup helps to reproduce your problem for us locally.

Unrelated to this issue: Does the tutorial work for you? https://symflower.com/en/products/symflower-cli/tutorial/intellij-java

**Comment by robertregina59** [comment]
I am using a separate settings.xml file which I am able to define in intellij settings: 

![image](https://user-images.githubusercontent.com/54856512/184226644-9db3d2b6-5ed9-48ee-89eb-c554c4078823.png)

**Comment by zimmski** [comment]
@robertregina59 we are looking into this.

**Comment by zimmski** [comment]
It seems that we are overwriting Maven's settings somehow in the wrong way. Which leads to not inheriting settings. We have some features/bugs before this, but have a good idea on how to make this work in general.

**Comment by zimmski** [comment]
AFAIK this should have been fixed a while ago buy some unrelated dependency work. Please let me know if it works now.
