### ISSUE TITLE
Cannot find "java" binary when IntelliJ 2022.2.3 is used for generating unit tests

### ISSUE THREAD

**Issue by Xanaxiel** [symflower/symflower#16]
Hey there, I came across your plugin and wanted to give it a spin since it might boost my productivity, but I'm getting this error when trying to generate tests on a file. Is there some extra steps in configuration/setup that I need to do? I'm using IntelliJ Ultimate 2022.2.3

```
Search for Java files
internal error: exec: "java": cannot run executable found relative to current directory
	data: C:\Users\HPI5~1\AppData\Local\Temp\symflower-java-parser1743536382\valid\
```

**Comment by magicprinc** [comment]
Same problem!

Latest IDEA Ultimate, latest version of plugin (installed today)

`Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xe8, 0x97, 0xe0, 0x0, 0x49, 0x9d, 0x11, 0xed, 0xb1, 0x65, 0x0, 0xff, 0x2e, 0x3b, 0xa, 0x16}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace C:\opt\D_REPO\fink-lab\
Search for Java files
internal error: exec: "java": cannot run executable found relative to current directory
	data: C:\tmp\symflower-java-parser987900120\valid\
Sending request(symflower/refresh-files)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xe8, 0x97, 0xe0, 0x0, 0x49, 0x9d, 0x11, 0xed, 0xb1, 0x65, 0x0, 0xff, 0x2e, 0x3b, 0xa, 0x16}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
`

**Comment by Xanaxiel** [comment]
@zimmski @bauersimon Hope you guys could look into this.

On a side note I tried using the CLI too to no avail

```
C:\path\to\project
λ symflower.exe src\SomeTestFile.java
Analyzing workspace C:\path\to\project
Search for Java files
Load dependency stdlib:@dev
internal error: unsupported AST node
        data: unsupported
Analyzed 0 out of 0 source files
Generated 0 tests, of which 0 reveal potential problems
The following issues prevent a full analysis:

* 1 case of "other issues"
        Description: Uncategorized problems.
```

Not sure where the logs are stored at so I can't provide any more details sadly on the `unsupported AST node`

**Comment by billbz99** [comment]
I also can't get it to work, I'm using IntelliJ Ultimate 2022.2.3
 
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x98, 0x9b, 0x76, 0x39, 0x4b, 0xc7, 0x11, 0xed, 0x9d, 0x4, 0xf8, 0xb4, 0x6a, 0xa1, 0x26, 0xa5}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace C:\Users\billb\Desktop\jpa-demo\jpa-demo\
Search for Java files
internal error: exec: "java": cannot run executable found relative to current directory
	data: C:\Users\billb\AppData\Local\Temp\symflower-java-parser4053526251\valid\
Sending request(symflower/refresh-files)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x98, 0x9b, 0x76, 0x39, 0x4b, 0xc7, 0x11, 0xed, 0x9d, 0x4, 0xf8, 0xb4, 0x6a, 0xa1, 0x26, 0xa5}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})

**Comment by zimmski** [comment]
Hey @Xanaxiel @magicprinc and @billbz99!

Thanks for reporting this problem and sorry for taking a bit to answer. I am just catching up with mails.

There seems to be two problems at work here. Let's go with the easiest first: The "java" not found problem should be related to your environment. Hence, we need to find out why Symflower cannot find your "java" binary in IntelliJ. Good news is that environment problems are usually easy to fix. Can you answer the following questions for me please?

- a. Which version of the Symflower plugin have you installed?
- b. How did you install Java?
- c. How did you install IntelliJ?
- d. Please install the CLI version of Symflower https://symflower.com/en/products/symflower-cli/tutorial/cli-java/#installation-tab-windows so we can run some commands (you can also use the "symflower.exe" from the IntelliJ plugin, but the locations depends on your IntelliJ setup). What is the output of "symflower version"?
- e. Again with the CLI version of Symflowre: Can you create a directory "foobar" and put a file "Copy.java" in it with the content of https://symflower.com/en/products/symflower-cli/tutorial/intellij-java/#tutorial When you then in the directory run "symflower Copy.java", what is the output of the command?

The answers to a.+b.+c.. should allow us to reproduce your environment, and the answers to d.+e. should make sure that we can reproduce the problem outside of IntelliJ.

**Comment by billbz99** [comment]
Hi @zimmski, here's my setup:
a. Symflower version 4.67
b. I think I installed Java from the oracle website but don't quite remember
c. I installed IntelliJ with the JetBrains toolbox app.

I followed d + e and was able to generate the file: CopySymflowerTest.java:
C:\dev\foobar>symflower Copy.java
Checking for updates
Latest version already installed
Analyzing workspace C:\dev\foobar
Search for Java files
Load dependency stdlib:@dev
Found 1 Java files
Found 0 problems in Java files
Copy.java: found 1 symbols
Copy.java: Copy.copy: computing test cases
Copy.java: Copy.copy: computed 1 unit tests
Copy.java: Copy.copy: found 0 problems
Symflower's table driven test style is not supported, switching to basic style
Copy.java: generated unit test file CopySymflowerTest.java
Analyzed 1 out of 1 source files
Generated 1 tests, of which 0 reveal potential problems
←[0;34mGive us your feedback and let us know how we can improve Symflower at hello@symflower.com or https://github.com/symflower/symflower.←[0m

But it doesn't work from IntelliJ
What are the next steps?

**Comment by Xanaxiel** [comment]
> a. Which version of the Symflower plugin have you installed?
25825

> b. How did you install Java?
I got multiple versions and switch between them, some via manual setup, some within IntelliJ, some 

> c. How did you install IntelliJ?
Via their installer, but already had gone through a lot of version updates (not sure if that messes up some path vars)

> d. Please install the CLI version of Symflower https://symflower.com/en/products/symflower-cli/tutorial/cli-java/#installation-tab-windows so we can run some commands (you can also use the "symflower.exe" from the IntelliJ plugin, but the locations depends on your IntelliJ setup). What is the output of "symflower version"?
```
symflower v25825 on windows/amd64

BuildVersion: 19044.2130
ProductName: Windows 10 Pro
ProductVersion: 6.3
ProductVersionMajor: 10
ProductVersionMinor: 0
Give us your feedback and let us know how we can improve Symflower at hello@symflower.com or https://github.com/symflower/symflower.
```

> e. Again with the CLI version of Symflowre: Can you create a directory "foobar" and put a file "Copy.java" in it with the content of https://symflower.com/en/products/symflower-cli/tutorial/intellij-java/#tutorial When you then in the directory run "symflower Copy.java", what is the output of the command?

```
Analyzing workspace C:\Users\Xanaxiel\Desktop\foobar
Search for Java files
Load dependency stdlib:@dev
Found 1 Java files
Found 0 problems in Java files
Copy.java: found 1 symbols
Copy.java: Copy.copy: computing test cases
Copy.java: Copy.copy: computed 1 unit tests
Copy.java: Copy.copy: found 0 problems
Symflower's table driven test style is not supported, switching to basic style
Copy.java: generated unit test file CopySymflowerTest.java
Analyzed 1 out of 1 source files
Generated 1 tests, of which 0 reveal potential problems
Give us your feedback and let us know how we can improve Symflower at hello@symflower.com or https://github.com/symflower/symflower.
```

**Comment by zimmski** [comment]
> I got multiple versions and switch between them, some via manual setup downloading from OpenJDK/Oracle, some within IntelliJ, some via scoop package manager but I got all of them in one jdk folder

@Xanaxiel how do you switch between them? That might be the key to this problem.

**Comment by zimmski** [comment]
We are actively working on this issue and looking into using IntelliJ directly to where the binaries we need (e.g. java.exe, mvn.exe, ...). Additionally, we will implement the logic of this page as a fallback https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by Xanaxiel** [comment]
> > I got multiple versions and switch between them, some via manual setup downloading from OpenJDK/Oracle, some within IntelliJ, some via scoop package manager but I got all of them in one jdk folder
> 
> @Xanaxiel how do you switch between them? That might be the key to this problem. E.g. are you selecting the JDK within IntelliJ or through some other functionality?

Via switching the `Project SDK` in _File > Project Structure_ settings or if per module, in the same window under _Modules > (select module) > Dependencies > Module SDK_

**Comment by zimmski** [comment]
@Xanaxiel @magicprinc and @billbz99 we added a workaround until we fully solved the problem for all environments. Can one of you please give me feedback if it is working for you now?

There is now also an additional entry in the Symflower log of the extension which shows us your PATH variable. This would be really helpful to have, to further investigate which environments we are missing in our testing environments. E.g. for me the log now starts with

```
Initializing language server
symflower v25998 on linux/amd64

KernelVersion: 5.14.21-150400.24.21-default
PATH: /home/zimmski/.vscode/extensions/symflower.symflower-0.0.25998-linux-x64/share/install/bin:/home/zimmski/symflower/src/gitlab.nethead.at/symflower/symflower/bin:/home/zimmski/symflower/src/github.com/symflower/garden/bin:/home/zimmski/symflower/build/nodejs/bin:/home/zimmski/symflower/bin:/home/zimmski/symflower/go/bin:/home/zimmski/.local/bin:/home/zimmski/.local/bin:/home/zimmski/.local/bin:/usr/local/bin:/usr/bin:/bin:/home/zimmski/symflower/src/gitlab.nethead.at/symflower/symflower/public/node_modules/.bin:/home/zimmski/symflower/conf/js/node_modules/.bin
```

One of these entries in the PATH variable is the culprit.

**Comment by Xanaxiel** [comment]
@zimmski Thanks a lot! Seems to be running now, I'll play around with the plugin once generation is done for one of the legacy god classes I'm refactoring and I'll let you know if I run into any issues

![image](https://user-images.githubusercontent.com/19189593/197706978-4b731b88-30d6-4441-87d8-26f96fcd6364.png)

**Comment by Xanaxiel** [comment]
One thing I noticed though is that it causes high CPU and memory usage when generating a test (might be related to https://github.com/symflower/symflower/issues/17)

Seems to be running though, I can see some `error: unknown field/type/function` come up in the logs but hopefully this would at least successfully generate some tests that I could start to work with.

![image](https://user-images.githubusercontent.com/19189593/197708194-e76320e1-646b-477c-a993-c155f08f0f22.png)

**Comment by Xanaxiel** [comment]
Awesome! I get a lot of these `// TODO This is a fallback value due to incomplete analysis.` but it generates tests now, could make do with this for scaffolds at the very least but it looks promising!
