### ISSUE TITLE
Cannot generate test template because of JNI related code

### ISSUE THREAD

**Issue by zimmski** [symflower/symflower#20]
### Discussed in https://github.com/symflower/symflower/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **richardhlavica** October 27, 2022</sup>
Hi sumflower team,
we started to use your great plugin in intelliJ but it does not generate any tests :(
**All info we have from the sumflower console is:** 
Handling request(2, "symflower/unit-test-skeleton")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x3c, 0xc, 0x5c, 0x45, 0x55, 0xd5, 0x11, 0xed, 0xbd, 0x92, 0x0, 0x5, 0x9a, 0x3c, 0x7a, 0x0}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit test skeletons...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace C:\Data\bitbucketWorkspace\uecommon\
Search for Java files
internal error: cannot parse JSON: cannot parse array: missing ',' after array value; unparsed tail: "s][warning][jni,resolve] Re-registering ...;)V from code in a different classloader"
Responding to request(2, "symflower/unit-test-skeleton")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x3c, 0xc, 0x5c, 0x45, 0x55, 0xd5, 0x11, 0xed, 0xbd, 0x92, 0x0, 0x5, 0x9a, 0x3c, 0x7a, 0x0}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})

I tried generate test for whole class and also for just a function but without any success :(
But generating function tests works with VisualStudio.

**Info about sumflower from console:**
Initializing language server
symflower v26016 on windows/amd64

BuildVersion: 19044.2130
Path: C:\Users\zbfygn\AppData\Roaming\JetBrains\IntelliJIdea2022.2\plugins\Symflower\share\install\bin;C:\oracle\oracle32\product\12.1.0\client_1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Data\apache-maven-3.6.3\bin;;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\zbfygn\AppData\Local\Microsoft\WindowsApps;C:\Users\zbfygn\AppData\Local\Yarn\bin;C:\Users\zbfygn\AppData\Roaming\npm;C:\Users\zbfygn\AppData\Local\Programs\Microsoft VS Code\bin
ProductName: Windows 10 Enterprise
ProductVersion: 6.3
ProductVersionMajor: 10
ProductVersionMinor: 0
Handling request(1, "initialize")
Acceptable workspace: uecommon (C:\Data\bitbucketWorkspace\uecommon\)

Any suggestion where could be the problem?</div>

**Comment by zimmski** [comment]
Currently waiting on user info https://github.com/symflower/symflower/discussions/19?sort=new#discussioncomment-3981567

**Comment by Xanaxiel** [comment]
Bumping on this as this might be related.

When I have the `Enable unit test generation upon saving a file` setting in Symflower settings unchecked, I can't generate a test on either context menus via right-clicking the file in the project explorer, or right-clicking within the file.

It works though when I have it checked (though this should also be working fine as for large classes it takes a lot of time and memory to generate one).

Logs I get below:
```
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xa2, 0xee, 0x4b, 0x77, 0x55, 0xfd, 0x11, 0xed, 0x81, 0xc0, 0x0, 0xff, 0x94, 0xb7, 0xdf, 0xe8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating unit tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xa2, 0xee, 0x4b, 0x77, 0x55, 0xfd, 0x11, 0xed, 0x81, 0xc0, 0x0, 0xff, 0x94, 0xb7, 0xdf, 0xe8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
```

**Comment by zimmski** [comment]
@Xanaxiel thanks for the message, these sound all like different problems since you are not receiving the "cannot parse JSON" error. Will comment one by one, and will add issues for your problems after #20.

> When I have the Enable unit test generation upon saving a file setting in Symflower settings unchecked, I can't generate a test on either context menus via right-clicking the file in the project explorer, or right-clicking within the file.

That sounds like a bug in how we enable functionality.

> It works though when I have it checked (though the option toggle should also be working fine to generate tests manually but it looks like a bug ...

Yep, sound likes a bug to me in how we enable functionality.

> as for large classes it takes a lot of time and memory to generate one).

That could be a problem of other components e.g. import/dependency handling. Let's dig into that after #20 and the bug for enabling functionality.

**Comment by richardhlavica** [comment]
For me the v26041 of symflower fixed the bug :)
Thank you all :)

**Comment by bauersimon** [comment]
Fixed with `v26041`.
