### ISSUE TITLE
Not working for intellij ultimate 2022.3 GO lang behind corp proxy

### ISSUE THREAD

**Issue by matz895** [symflower/symflower#23]
Intellij network settings are ok and working fine connecting outside proxy, and to internal servers. Im behind a corporate proxy.
symflower version 26791

Starting:
Checking for updates
cannot check for updates: cannot download version file: Get "https://download.symflower.com/local/latest/version": dial tcp 116.202.234.38:443: i/o timeout
Initializing language server
symflower v26791 on linux/amd64

Then: 
KernelVersion: 5.15.0-56-generic
PATH:  Symflower plugin binary etc...
ProductName: Ubuntu
ProductVersion: 20.04
Handling request(1, "initialize")
Failed to send environment data: Post "https://api.symflower.com/v1/telemetry/environment": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Here I start Symflower: Generate Unit Tests for File   (Context menu choice on one go file in my project)
Acceptable workspace: backend-service (/home/u057166/dev/backend-service/)
Responding to request(1, "initialize")
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification($/progress)
Unit test generation on save is disabled.
Sending notification($/progress)

**Comment by bauersimon** [comment]
Hi @matz895 thank you for this report. Can you please clarify if only the self-update functionality is broken or if you're also not able to generate any tests / templates using Symflower?

**Comment by matz895** [comment]
Thanks for the quick response. When I use generate test for a function, the plugin generates a test. But when I try the option for generating tests for a file, nothing happens.

**Comment by bauersimon** [comment]
@matz895 the issue you're facing when generating tests for a file is actually a know bug that we fixed with yesterdays release. So if you update the plugin via the IntelliJ marketplace to version `26808` or higher, that should be fixed. Could you try that?

**Comment by matz895** [comment]
what happened? Did you remove the function that was not working for me?

**Comment by matz895** [comment]
These are the options from the context menu, The first one does not work, the second work as before.
![image](https://user-images.githubusercontent.com/73602025/208067190-0f71aa98-2941-4c87-a183-9d1651096cc0.png)

**Comment by zimmski** [comment]
Users that are using the free version of Symflower are required to send metrics and problems of Symflower, i.e. for proxies we need to know how the proxy is configured.

The functionality never was removed, we just renamed a few context menu entries and moved some into actions/commands to not clutter the context menu.
