### ISSUE TITLE
Cannot generate tests for file if test generation on save is disabled

### ISSUE THREAD

**Issue by bauersimon** [symflower/symflower#24]
[Reported](https://github.com/symflower/symflower/issues/20#issuecomment-1293557117) by @Xanaxiel in #20.

If test generation on save is disabled in the settings, no tests are generated when choosing test generation for a whole file in any editor.

This should be fixed now with version `26808`.

**Comment by bauersimon** [comment]
@Xanaxiel since you reported this originally could you verify if this works now, will then close this issue.

**Comment by zimmski** [comment]
This is our default for a long long time now.  Should be fine.
