### ISSUE TITLE
Could you please provide a change log for the different releases?

### ISSUE THREAD

**Issue by matz895** [symflower/symflower#25]
Hi. Would be nice to know what is happening between the different versions of the intellij plugin that I install. I cannot see that it is availabile on the jetbrains plugin site. But perhaps I am just not seeing it?

Thanks!

**Comment by zimmski** [comment]
@matz895 You can find the public changelog here https://docs.symflower.com/docs/changelog/.

Sorry for taking so long to write back. There have been lots of changes to the company and especially to Symflower in the last months, we needed to prioritize our efforts. Now that we caught up, we are working down our public queue with focus on issues of advocates, who are giving us direct feedback. I would be very happy if you would join us by writing me at markus.zimmermann@symflower.com
