### ISSUE TITLE
kotlin support

### ISSUE THREAD

**Issue by humazed** [symflower/symflower#27]
Are there any plans to add kotlin support?

**Comment by EnvyIT** [comment]
+1 Would be really interesting if we get support for Kotlin too.

Workaround for now:

1. Generate a Java class -> Let Symflower generate the test suite.
3. Convert files to Kotlin.

**Comment by zimmski** [comment]
I am sorry to say that until we have a payed project hat supports the implementation of a new language, we are not working on a new language. It is a simple matter of how many people we are. Our current focus is Java and adding more and more UX features to showcase how our technologies can be used with Java (and Go).

**Comment by EnvyIT** [comment]
Anyway, thanks for your explanation.
