### ISSUE TITLE
Implement "go modules"

### ISSUE THREAD

**Issue by loves-bruins** [symflower/symflower#28]
Occurs on both Goland and VSCode:

I am getting same errors with Goland 2022.3.1 and VSCode.  It seems to be looking at my workspace folder to resolve modules.

`Initializing language server
symflower v27903 on darwin/arm64

BuildVersion: 21G419
KernelVersion: 21.6.0
PATH: /Users/lrogers/Library/Application Support/JetBrains/GoLand2022.3/plugins/Symflower/share/install/bin:/usr/bin:/bin:/usr/sbin:/sbin
ProductName: macOS
ProductVersion: 12.6.3
Handling request(1, "initialize")
Acceptable workspace: event-data-validator (/Users/lrogers/dev/b2/b2cm/event-data-validator/)
Responding to request(1, "initialize")
Handling request(2, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd1, 0xd5, 0x13, 0x86, 0xb6, 0xc3, 0x11, 0xed, 0xb0, 0x35, 0xde, 0x78, 0x55, 0x98, 0x52, 0x29}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /Users/lrogers/dev/b2/b2cm/event-data-validator/
Search for Go files
Load dependency stdlib:@dev
internal/schema/validator.go:24:13: error: undeclared name: jsonschema
internal/schema/validator.go:33:28: error: undeclared name: jsonschema
internal/schema/validator.go:33:50: error: undeclared name: jsonschema
internal/schema/validator.go:65:28: error: undeclared name: jsonschema
internal/schema/validator.go:82:33: error: undeclared name: jsonschema
internal/schema/validator.go:98:38: error: undeclared name: jsonschema
internal/schema/validator.go:59:14: error: undeclared name: jsonschema
internal/schema/validator.go:60:19: error: undeclared name: jsonschema
internal/schema/validator.go:16:2: error: could not import encoding/json (cannot find package "encoding/json" in any of:
($GOROOT not set)
/Users/lrogers/dev/b2/b2cm/event-data-validator/src/encoding/json (from $GOPATH))
internal/schema/validator.go:17:2: error: could not import event-data-validator/config (cannot find package "event-data-validator/config" in any of:
($GOROOT not set)
/Users/lrogers/dev/b2/b2cm/event-data-validator/src/event-data-validator/config (from $GOPATH))
internal/schema/validator.go:18:2: error: could not import fmt (cannot find package "fmt" in any of:
($GOROOT not set)
/Users/lrogers/dev/b2/b2cm/event-data-validator/src/fmt (from $GOPATH))
internal/schema/validator.go:19:2: error: could not import path (cannot find package "path" in any of:
($GOROOT not set)
/Users/lrogers/dev/b2/b2cm/event-data-validator/src/path (from $GOPATH))
internal/schema/validator.go:21:2: error: could not import github.com/santhosh-tekuri/jsonschema/v5 (cannot find package "github.com/santhosh-tekuri/jsonschema/v5" in any of:
($GOROOT not set)
/Users/lrogers/dev/b2/b2cm/event-data-validator/src/github.com/santhosh-tekuri/jsonschema/v5 (from $GOPATH))
Found 1 Go files
Found 13 problems in Go files
internal/schema/validator.go: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x1, Message:"Unknown error. Please check the Symflower log for more details."})
Responding to request(2, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd1, 0xd5, 0x13, 0x86, 0xb6, 0xc3, 0x11, 0xed, 0xb0, 0x35, 0xde, 0x78, 0x55, 0x98, 0x52, 0x29}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
`

**Comment by freephenix** [comment]
I  have the same question! What is your go version?

**Comment by zimmski** [comment]
Unfortunately we did not fully implement Go modules and with that some of the import/dependency logic that Go requires of us. We currently focus on Java. However, if there is a company that is willing to do a payed Go project with us, i am happy to make all of this work. Until then, we need to focus unfortunately since we are only so few people.
