### ISSUE TITLE
Plugin for IntelliJ IDEA

### ISSUE THREAD

**Issue by zimmski** [symflower/symflower#3]
Provide a plugin of "symflower" that let's you generate tests with IntelliJ IDEA.

If you are interested in this feature, please give a thumbs up.

**Comment by zimmski** [comment]
Thanks for voting on this feature request! This feature has been implemented in Symflower CLI. You can use it starting with version 21957 (Beginning with 22295 we also support IntelliJ IDEA 2022.x). You can find the feature page here https://symflower.com/en/products/symflower-cli/getting-started/intellij-java/ and the tutorial here https://symflower.com/en/products/symflower-cli/tutorial/intellij-java/ The official Goland beta is on its way.

Please give it a try and let me know how it went! The IntelliJ plugin is not yet on the same functionality level with Visual Studio Code but give us an iteration and we then keep it in sync for the future.

@pgreitbauer @elHiaso @pf0 would highly appreciate your feedback on this

**Comment by pgreitbauer** [comment]
Hi,
great that you also provide an IntelliJ plugin now.
If I find the time I will give it a spin ;)
Do you have a feature comparison table for VSCode vs IntelliJ?

**Comment by zimmski** [comment]
@pgreitbauer right now we only support the generation of unit tests (in comparison to automatic maintenance of manual written tests, test templates, showing traces for problems, (soon) showing coverage for individual tests, direct debugging of test cases, reviewing of generated tests, ...) I think, it would be worth simply doing a session to show you what we have in store. Would you be up for that?

**Comment by zimmski** [comment]
@pgreitbauer @elHiaso @pf0 @JukicDejan JetBrains has enabled the update of our extension that supports IntelliJ 2022.x. The next updates are queued but the release process has some manual steps on JetBrains' side it takes a few days. Don't think we can do anything about that.

Please let me know if the tutorial works. We are already working on enabling more features.
