### ISSUE TITLE
Generated Tests for Methods with LocalDate are initialized with null

### ISSUE THREAD

**Issue by JukicDejan** [symflower/symflower#30]
See the generated Tests and the example project:

https://github.com/JukicDejan/symflower-test/blob/master/src/test/java/com/example/demo/utils/DateUtilsSymflowerTest.java

Log from the Symflower tab:

Checking for updates
[0;30m[0;102mThere is a new version of symflower available! Please run `symflower update`.[0m
Initializing language server
symflower v29118 on linux/amd64

KernelVersion: 5.4.0-139-generic
PATH: /home/jd/.jdks/adopt-openjdk-11.0.10/bin:/home/jd/.cargo/bin:/home/jd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/jd/go/bin:/usr/lib/jvm/default-java/bin:/home/jd/.local/share/JetBrains/Toolbox/scripts
ProductName: Linux Mint
ProductVersion: 19
Handling request(1, "initialize")
Acceptable workspace: customer-data-service (/home/jd/edeka/customer-data-service/)
Responding to request(1, "initialize")
Handling notification(workspace/didChangeWorkspaceFolders)
Acceptable workspace:  (/home/jd/edeka/system-test/)
Added workspace path: /home/jd/edeka/system-test/
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb5, 0x50, 0x9b, 0xb2, 0xd9, 0xcf, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb5, 0x50, 0x9b, 0xb2, 0xd9, 0xcf, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xcd, 0x17, 0x3f, 0xd, 0xd9, 0xcf, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xcd, 0x17, 0x3f, 0xd, 0xd9, 0xcf, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(workspace/didChangeWorkspaceFolders)
Acceptable workspace:  (/home/jd/edeka/system-test/)
Removed workspace path: /home/jd/edeka/system-test/
Handling notification(workspace/didChangeWorkspaceFolders)
Acceptable workspace:  (/home/jd/edeka/terraform/)
Added workspace path: /home/jd/edeka/terraform/
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x6d, 0xfd, 0x77, 0xca, 0xd9, 0xd4, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x6d, 0xfd, 0x77, 0xca, 0xd9, 0xd4, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x3e, 0x68, 0x81, 0xec, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x3e, 0x68, 0x81, 0xec, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x56, 0xea, 0x5b, 0x85, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x56, 0xea, 0x5b, 0x85, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x90, 0x6f, 0xec, 0xea, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x90, 0x6f, 0xec, 0xea, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb8, 0xf3, 0x4e, 0x34, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb8, 0xf3, 0x4e, 0x34, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xcf, 0x32, 0x95, 0x33, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xcf, 0x32, 0x95, 0x33, 0xd9, 0xd7, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd0, 0x92, 0xb, 0x1c, 0xd9, 0xde, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd0, 0x92, 0xb, 0x1c, 0xd9, 0xde, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(workspace/didChangeWorkspaceFolders)
Acceptable workspace:  (/home/jd/symflower-demo/demo/)
Added workspace path: /home/jd/symflower-demo/demo/
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd8, 0xf4, 0x4f, 0xb9, 0xda, 0xc3, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd8, 0xf4, 0x4f, 0xb9, 0xda, 0xc3, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x6f, 0xe5, 0xf6, 0x3e, 0xda, 0xc4, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x6f, 0xe5, 0xf6, 0x3e, 0xda, 0xc4, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling request(2, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x7c, 0x74, 0xd6, 0xbc, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
Load dependency stdlib:@dev
Found 1 Java files
Found 0 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x2, Message:"No function selected that should be analyzed."})
Responding to request(2, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x7c, 0x74, 0xd6, 0xbc, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling request(3, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x80, 0x89, 0xd6, 0xa2, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
Found 1 Java files
Found 0 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x2, Message:"No function selected that should be analyzed."})
Responding to request(3, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x80, 0x89, 0xd6, 0xa2, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling request(4, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x84, 0x6c, 0xfd, 0xa5, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
Found 1 Java files
Found 0 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x2, Message:"No function selected that should be analyzed."})
Responding to request(4, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x84, 0x6c, 0xfd, 0xa5, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling request(5, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x88, 0xc5, 0x64, 0x59, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
Found 1 Java files
Found 0 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 0 symbols
Sending notification(method: window/showMessage, data: lsp.ShowMessageParams{Type:0x2, Message:"No function selected that should be analyzed."})
Responding to request(5, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x88, 0xc5, 0x64, 0x59, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x8b, 0x8f, 0x31, 0xc2, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0x8b, 0x8f, 0x31, 0xc2, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(symflower/filesClosed)
Handling notification(workspace/didChangeWorkspaceFolders)
Acceptable workspace:  (/home/jd/edeka/customer-data-service/)
Handling notification(symflower/filesClosed)
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb6, 0xd8, 0xf1, 0xbd, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb6, 0xd8, 0xf1, 0xbd, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb8, 0x3d, 0xf3, 0x8c, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xb8, 0x3d, 0xf3, 0x8c, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xc5, 0xdc, 0x7, 0xd3, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xc5, 0xdc, 0x7, 0xd3, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(textDocument/didSave)
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd2, 0xce, 0x69, 0xb9, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Unit test generation on save is disabled.
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xd2, 0xce, 0x69, 0xb9, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling request(6, "symflower/unit-test-skeleton")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xf0, 0x2a, 0x43, 0x76, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Adding test templates...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
Found 1 Java files
Found 0 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 1 symbols
Symflower's table driven test style is not supported, switching to basic style
src/test/java/com/example/demo/utils/DateUtilsTest.java: generated test at src/test/java/com/example/demo/utils/DateUtilsTest.java:8:29
src/main/java/com/example/demo/utils/DateUtils.java: generated unit test file src/test/java/com/example/demo/utils/DateUtilsTest.java
Responding to request(6, "symflower/unit-test-skeleton")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xf0, 0x2a, 0x43, 0x76, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)
Handling request(7, "symflower/unit-test")
Sending request(window/workDoneProgress/create)
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xf8, 0x22, 0xe8, 0xf3, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressBegin{Kind:"begin", Title:"Generating tests...", Cancellable:false, Message:"", Percentage:0x0}})
Analyzing workspace /home/jd/symflower-demo/demo/
Search for Java files
src/main/java/com/example/demo/utils/DateUtils.java: error: unknown import
	data: java/time/LocalDate
src/main/java/com/example/demo/utils/DateUtils.java: error: unknown import
	data: java/time/temporal/ChronoUnit
Found 1 Java files
Found 2 problems in Java files
src/main/java/com/example/demo/utils/DateUtils.java: found 1 symbols
src/main/java/com/example/demo/utils/DateUtils.java: com.example.demo.utils.DateUtils.numberOfPeriods: computing test cases
src/main/java/com/example/demo/utils/DateUtils.java: com.example.demo.utils.DateUtils.numberOfPeriods: computed 0 unit tests
src/main/java/com/example/demo/utils/DateUtils.java: com.example.demo.utils.DateUtils.numberOfPeriods: generated unit test template containing zero values
src/main/java/com/example/demo/utils/DateUtils.java: com.example.demo.utils.DateUtils.numberOfPeriods: found 1 problems
src/main/java/com/example/demo/utils/DateUtils.java: internal error: com.example.demo.utils.DateUtils.numberOfPeriods: unknown type kind
	data: unsupported(java/time/LocalDate)
Symflower's table driven test style is not supported, switching to basic style
src/main/java/com/example/demo/utils/DateUtils.java: generated unit test file src/test/java/com/example/demo/utils/DateUtilsSymflowerTest.java
Sending request(symflower/refresh-files)
Responding to request(7, "symflower/unit-test")
Sending notification(method: $/progress, data: lsp.ProgressParams{Token:uuid.UUID{0xf8, 0x22, 0xe8, 0xf3, 0xda, 0xc5, 0x11, 0xed, 0xa5, 0x82, 0xe8, 0x6a, 0x64, 0x50, 0xb2, 0x8}, Value:lsp.WorkDoneProgressEnd{Kind:"end", Message:""}})
Handling notification(symflower/filesClosed)

**Comment by zimmski** [comment]
@JukicDejan we now initialize "LocaleDate" objects with `LocalDate.of`. Work is under way to cover all standard library and dependency constructors. Pretty exciting to finally get this done. Let me know if you find anything else! There have been tons of changes: https://docs.symflower.com/docs/changelog/
