### ISSUE TITLE
Symflower: Could not find binary

### ISSUE THREAD

**Issue by drakgoku** [symflower/symflower#36]
Doesn't work in VSC
When I open VSC I see this warning:
`Symflower: Could not find binary:  c:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe`
The folder exists and there is the symflower file type archive.

If I try to generate the code I get the error:
Symflower: Connection to the language server is not active

**Comment by drakgoku** [comment]
I think this app on github is dead.

It's time to look for another alternative.

**Comment by zimmski** [comment]
Not dead, just really busy with projects (e.g. [this](https://x.com/zimmskal/status/1809197183469515151) and [those](https://x.com/zimmskal/status/1808449095884812546) and [that](https://symflower.com/en/company/blog/2024/dev-quality-eval-v0.5.0-deepseek-v2-coder-and-claude-3.5-sonnet-beat-gpt-4o-for-cost-effectiveness-in-code-generation/)). We will update the changelog soonish though, but we are constantly uploading fixes and new features. Just saving time with not announcing too much.

@drakgoku About your bug. This should be a pretty easy one. Can you upload the extension log please ("OUTPUT" Tab -> select "Symflower" and then the whole content there).

**Comment by zimmski** [comment]
@drakgoku also, can you please try the following:
- open a terminal
- change directory to the root directory of your project
- run the binary like so `c:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe version`
- run the binary like so `c:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe symbols`

This should give us some more information on what could be the problem. If this runs through, then the answer should be in the VSCode log usually. Might be some Antivirus blocking us.

**Comment by drakgoku** [comment]
- Symflower output does not show anything. When it wants to generate or not, it does not show anything either. 
- Log execute:  C:\Users\Deliv\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe 

```
PS D:\Todo\..\..\2024\Project .....\.....> C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe  version
C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe : El término 
'C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe' no se reconoce como nombre de un cmdlet, función, 
archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha 
ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\.....\...n\symflower.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```


As I said, I don't have an .exe, I have a file type file.
- If I try to rename symflower to symflower.exe I get:
```
Error al ejecutar el programa 'symflower.exe': El ejecutable especificado no es una aplicación válida para esta plataforma de sistema 
operativo.En línea: 1 Carácter: 1
+ C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
En línea: 1 Carácter: 1
+ C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by drakgoku** [comment]
- Symflower output does not show anything. When it wants to generate or not, it does not show anything either. 
- Log execute:

```
PS D:\Todo\..\..\2024\Project .....\.....> C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe  version
C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe : El término 
'C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32-x64\bin\symflower.exe' no se reconoce como nombre de un cmdlet, función, 
archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha 
ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ C:\Users\.....\.vscode\extensions\symflower.symflower-0.0.39263-win32 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\.....\...n\symflower.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by grihenrik** [comment]
.vscode\extensions\symflower.symflower-0.0.39534-win32-x64\bin\symflower.exe version
ResourceUnavailable: Program 'symflower.exe' failed to run: An error occurred trying to start process 'C:\Users\henrik.gripenberg\.vscode\extensions\symflower.symflower-0.0.39534-win32-x64\bin\symflower.exe' with working directory 'C:\Users\henrik.gripenberg'. The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .vscode\extensions\symflower.symflower-0.0.39534-win32-x64\bin\symflo …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
After I renamed symflower to symflower.exe

**Comment by zimmski** [comment]
@drakgoku and @grihenrik thanks! "The specified executable is not a valid application for this OS platform" sounds like the problem. can you tell me your CPUs? Maybe we are using the wrong architecture binary for you.

**Comment by grihenrik** [comment]
I am using a x86 cloud pc (Epyc based)

**Comment by drakgoku** [comment]
The same thing happens for Ryzen APU.

**Comment by zimmski** [comment]
Thanks very much! We found the problem. Currently adding some more test and need to wait for the CI then. Will close the issue when release is out.

The culprit was a change in how we package that selected the wrong artifact.

**Comment by zimmski** [comment]
Thanks for your patience and information. This problem should be solved with version 39798!

@drakgoku and @grihenrik could you please give it a try. Great start would be our Java tutorial https://symflower.com/en/products/symflower-cli/tutorial/vscode-java/ which should give you a good overview on common Symflower features. Let me know how it went. I am also always up for a video session to see cases we do not support yet.

**Comment by drakgoku** [comment]
The same thing happens. But it creates the file with one function when it should really have created at least 13 functions.
And we're talking about a simple CRUD.
![image](https://github.com/user-attachments/assets/30753d43-efe9-4fb2-9b5c-ef8396db8bf4)

**Comment by drakgoku** [comment]
Is this solved?
![image](https://github.com/user-attachments/assets/fc47de40-b47d-4a0a-9d30-fc6d75e8b08e)

I just tried right clicking "generate test suito for function".

What does work is "create test" method by method clicking one by one. To start with it makes the test wrong, but it works regardless.

**Comment by grihenrik** [comment]
It works for a simple test, however, even with the settings set I don’t
know how to get the ai test writing working.

Terveisin
Henrik

**Comment by drakgoku** [comment]
I'm using Gemini.
![image](https://github.com/user-attachments/assets/6ef93880-c70b-4c86-80c3-e91cd7e3169d)


I think I've given Symflower enough time to do it right and 2 months is already excessive, even more so with 2 days it seems excessive to me.
