### ISSUE TITLE
Enable imports/dependencies for the community version

### ISSUE THREAD

**Issue by zimmski** [symflower/symflower#6]
We currently disable imports and dependencies for the "Community" version of Symflower until the feature set caught up with the "Team" version, and we have the confidence that the "Community" version behaves the way it should.

**Comment by nagkumar** [comment]
`nagkumar@tejanag:/mnt/mt-java-pit-sample/kata$ symflower
src/main/java/kata/CompanyRunner.java: internal error: feature of import handling is disabled
src/main/java/kata/domain/Company.java: internal error: feature of import handling is disabled
src/test/java/kata/domain/tests/CompanyTest.java: internal error: feature of import handling is disabled
Could not generate unit test file for "src/main/java/kata/domain/Employee.java"`

I see this error, this way the first simple first example does not work..

**Comment by zimmski** [comment]
@nagkumar thanks for your comment. sorry for the long delay (baby arrived). We received already some feedback that this feature should be enabled as fast as possible for the free version. We are working on it! Can you maybe send me a link to your repository to markus.zimmermann@symflower.com so i can take a look earlier?

**Comment by nagkumar** [comment]
This is the code, I was trying Unit Tests Generation https://github.com/vmzakharov/mutate-test-kata

**Comment by aastorg2** [comment]
@zimmski I too face the same problem as @nagkumar.
is there an expected ETA for the feature?

**Comment by zimmski** [comment]
Hi. We are actively working on this for a while now. To give a little background: we are squeezing our test generation engine that is meant for a server cluster environment into a notebook environment with <2GB of memory for our analysis. Tough problem. It works for a wide range of scenarios but we like to keep the community version gated until we do not crunch too many resources.

**Comment by zimmski** [comment]
@vkhodygo can you add a link to the repository you want to test?

**Comment by vkhodygo** [comment]
@zimmski 
 > with <2GB of memory

I feel like many software engineers here don't mind sacrificing a little bit more resources to make their life easier. That also includes trying unstable versions of software. But that's obviously up to you.

I can share [it](https://github.com/jasmineRepo/JAS-mine-core), but it's pretty useless for most people: it's a legacy project with a lot of quirks, I'm putting it back on track. The latest release can be built, however, this is not the final version that needs tests.

**Comment by zimmski** [comment]
We do not enable this option by default yet, but we constantly adding options to generate more code including more dependencies. Please give it another go how well it works. Closing this issue for now since this is an ongoing issue and we are solving as many problems as we can with every version.
