### ISSUE TITLE
Symflower CLI does not work for Debian 10

### ISSUE THREAD

**Issue by zimmski** [symflower/symflower#7]
A user reported that Symflower CLI does not generate any tests on Debian 10 as a non-root user and does not output any reason to why that is.

**Comment by zimmski** [comment]
We identified three problems:
- Our installer script executed the "symflower" command as root in the user directory. Hence, all files belonged to root instead of the user.
- We have an internal error during the test generation under Debian. Will give an update soonish on this one.
- We are hiding internal errors.

Actions:
- Debian 10 is now part of our publishing tests.
- Install script has been fixed by executing only parts of it as root.
- We will make internal errors mostly public to the user.

**Comment by zimmski** [comment]
We identified at least one of the problems of "symflower" on Debian 10 to be the Z3 binary we are including with the binary. We are switching to a static build for the Linux binary.

**Comment by zimmski** [comment]
Symflower CLI now works with Debian 10 and other "older" distributions. Basically Symflower CLI is now an (almost) fully statically built binary. This is well worth the additional 2MB in size. ALL major Linux distributions should now be supported. So if you are seeing problems, please let us know.

```bash
sudo apt-get update
sudo apt-get install -y curl openjdk-11-jre procps
curl -sSLf https://get.symflower.com/install | sh # Currently requires "sudo", if you want a root-less install please let us know!
cd
mkdir src
cd src

cat > Copy.java <<- END
class Copy {
    static String[] copy(String[] from, String[] to) {
        return to;
    }
}
END
symflower
```

There were A LOT of changes needed to get this working:
- The installer script works now on any platform that supports Shell Script
- The installer script does now always use the correct user for installing
- Internal errors and other errors are now always reported and easier to look at
- Output of Symflower CLI has been greatly improved (there is another iteration coming soonish)
- For older distributions such as Debian 10 we needed a working solver (Z3 is what we are using) we are now doing a statically build for the solver
- And lots of smaller changes to fix bugs and improve UX.

All of this is of course automatically tested.

**Comment by chadbrewbaker** [comment]
The industry standard, given so many legacy versions of Java, is a JVM version manager like nvm for node. 

https://sdkman.io

I would use the sdkman set of binaries instead of Linux distro binaries as your JVM reference builds.

**Comment by chadbrewbaker** [comment]
Might be useful - how sdkman can run arbitrary JVMs for Github workers - from there you could pull in symflower and run it as part of the CI across a range of JVMs.

https://github.com/sdkman/sdkman-action
